# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/marishque-mouse',
                'doc_host': 'https://k111git.github.io',
                'git_url': 'https://github.com/k111git/marishque-mouse',
                'lib_path': 'marishque_mouse'},
  'syms': {'marishque_mouse.core': {'marishque_mouse.core.foo': ('core.html#foo', 'marishque_mouse/core.py')}}}