# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['Mouse', 'test_normal_case']

# %% ../00_core.ipynb 3
import time

# %% ../00_core.ipynb 5
class Mouse:
    "This is a cute mouse"
    def __init__(self
                 ,age #Age of the mouse
                 ,name #name of the mouse
                ):
        self.age=age
        self.name=name
    def __str__(self):
        return f"Mouse {self.name} is {self.age}"
    __repr__ = __str__
    def call(self,n:int=5):
        "Calls the cute `Mouse` `n` times"
        out="Mousi"
        for i in range(0,n):
            out=out+"i"
            print(f'{out}n')
            time.sleep(0.6)
        print(f'Mouse {self.name}, age {self.age} has been called')
            

# %% ../00_core.ipynb 13
# The test function to be executed by PyTest
def test_normal_case():
    mouse=Mouse(29,'Marishque')
    assert mouse.age == 29, "incorrect age"

# %% ../00_core.ipynb 14
test_normal_case()
